# Generated by Django 5.2.1 on 2025-08-17 18:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        ("tipoSacramentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        error_messages={"blank": "O Nome é obrigatório."},
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        error_messages={
                            "blank": "O CPF é obrigatório.",
                            "unique": "Este CPF já está cadastrado.",
                        },
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF inválido. Formato esperado: 000.000.000-00.",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        error_messages={"null": "A Data de Nascimento é obrigatória."},
                        verbose_name="Data de Nascimento",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        error_messages={"blank": "O campo Sexo é obrigatório."},
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "comunidade",
                    models.ForeignKey(
                        error_messages={"null": "A Comunidade deve ser selecionada."},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comunidades.comunidade",
                        verbose_name="Comunidade",
                    ),
                ),
                (
                    "tipo_sacramento",
                    models.ForeignKey(
                        error_messages={
                            "null": "O Tipo de Sacramento deve ser selecionado."
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tipoSacramentos.tiposacramento",
                        verbose_name="TipoSacramento",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pessoa",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
