# Generated by Django 5.2.1 on 2025-08-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        ("tipoEventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_evento",
                    models.CharField(max_length=100, verbose_name="Título do Evento"),
                ),
                (
                    "data_hora",
                    models.DateTimeField(verbose_name="Data e Hora do Evento"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Evento")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "comunidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="comunidades.comunidade",
                        verbose_name="Comunidade",
                    ),
                ),
                (
                    "tipo_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="tipoEventos.tipoevento",
                        verbose_name="Tipo de Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento no Calendário",
                "verbose_name_plural": "Eventos no Calendário",
                "ordering": ["-criado_em"],
            },
        ),
    ]
