# Generated by Django 5.2.1 on 2025-08-17 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        ("pessoas", "0001_initial"),
        ("tipoSacramentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sacramento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_hora",
                    models.DateTimeField(
                        max_length=100, verbose_name="Data e Hora do Sacramento"
                    ),
                ),
                (
                    "comunidade",
                    models.ForeignKey(
                        help_text="Comunidade do Sacramento",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comunidades.comunidade",
                        verbose_name="Comunidade",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        help_text="Pessoa do Sacramento",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pessoas.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_responsavel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "tipo_sacramento",
                    models.ForeignKey(
                        help_text="Tipo Sacramento do Sacramento",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tipoSacramentos.tiposacramento",
                        verbose_name="Tipo Sacramento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sacramento",
                "verbose_name_plural": "Sacramentos",
            },
        ),
    ]
