# Generated by Django 5.2.1 on 2025-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoSacramento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Tipo Sacramento",
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Tipo Sacramento",
                "verbose_name_plural": "Tipo Sacramentos",
            },
        ),
    ]
